# Ejercicios TensorFlow y Keras - Hugo Peralta Muñoz

## 1. Importa TensorFlow.

In [1]:
import tensorflow as tf

## 2. Importa Keras.

In [2]:
from tensorflow import keras

## 3. ¿Qué es un tensor en Tensorflow?

Un tensor en TensorFlow es una estructura de datos multidimensional que representa matrices y vectores n-dimensionales, utilizada para almacenar y manipular datos numéricos. Es el componente básico de la computación en TensorFlow, compatible con operaciones algebraicas y capaz de fluir a través de un modelo. Los tensores tienen propiedades como dimensiones (shape) y tipo de datos (dtype).

## 4. Crea dos tensores con valores aleatorios entre $0$ y $1$ y las dimensiones `[5, 300]`.

In [3]:
tensor1 = tf.random.uniform(shape=[5, 300], minval=0, maxval=1)
tensor2 = tf.random.uniform(shape=[5, 300], minval=0, maxval=1)

## 5. Multiplica los dos tensores del ejercicio anterior.

In [5]:
multiplied_tensors = tf.multiply(tensor1, tensor2)
multiplied_tensors

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.36898223, 0.00736399, 0.00514991, ..., 0.03295816, 0.12505898,
        0.8340466 ],
       [0.06835898, 0.00734587, 0.28862417, ..., 0.01196212, 0.12282009,
        0.06980941],
       [0.22706443, 0.0520004 , 0.10058136, ..., 0.05273278, 0.22387816,
        0.10917804],
       [0.2522772 , 0.08816355, 0.24552147, ..., 0.31966737, 0.11335851,
        0.00892074],
       [0.12379011, 0.17865397, 0.1486415 , ..., 0.06109536, 0.57405937,
        0.39064342]], dtype=float32)>

## 6. Averigua el mínimo, máximo, suma y media del primer tensor.

In [6]:
min_value = tf.reduce_min(multiplied_tensors)
max_value = tf.reduce_max(multiplied_tensors)
sum_value = tf.reduce_sum(multiplied_tensors)
mean_value = tf.reduce_mean(multiplied_tensors)

min_value, max_value, sum_value, mean_value

(<tf.Tensor: shape=(), dtype=float32, numpy=0.00016151912859641016>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9462977647781372>,
 <tf.Tensor: shape=(), dtype=float32, numpy=371.7823486328125>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.24785490334033966>)

## 7. Define un tensor con valor `[1, 2, 3]` y el tipo de datos `int32` y guarda el resultado en $x$.


In [7]:
x = tf.constant([1, 2, 3], dtype=tf.float32)

## 8. Calcula la traspuesta de un tensor $a$ y guárdalo en `a_transposed`. Prueba con el tensor `a = [[1, 2], [3, 4], [5, 6]]`.


In [8]:
a = tf.constant([[1, 2], [3, 4], [5, 6]], dtype=tf.float32)

a_transposed = tf.transpose(a)
a_transposed

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 3., 5.],
       [2., 4., 6.]], dtype=float32)>

## 9. Convierte el tensor $a$ en un array de numpy con nombre `a_np`.

In [9]:
a_np = a.numpy()
a_np

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float32)

## 10. Calcula la suma de todos los elementos del tensor `a` y guárdalo en `a_sum`.

In [13]:
a_sum = tf.reduce_sum(a)
a_sum

<tf.Tensor: shape=(), dtype=float32, numpy=21.0>

## 11. Calcula la media de todos los elementos del tensor `a` y guárdalo en `a_mean`.


In [14]:
a_mean = tf.reduce_mean(a)
a_mean

<tf.Tensor: shape=(), dtype=float32, numpy=3.5>

## 12. Define una variable de TensorFlow llamada `weights` con valor `[0.2, 0.8, 0.5]`.

In [15]:
weights = tf.constant([0.2, 0.8, 0.5])
weights

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.2, 0.8, 0.5], dtype=float32)>

## 13. Calcula la suma de dos tensores $a$ y $b$ y guarda el resultado en la variable result. Prueba con los tensores `a = [1, 2, 3]` y `b = [4, 5, 6]`.

In [18]:
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])

result = a + b

result

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9])>

## 14. Aplica la función softmax a un tensor $x$ y guarda el resultado en la variable `result`. Prueba con el tensor `x = [1.2, 3.0, 8.9]`.

In [22]:
x = tf.constant([1.2, 3.0, 8.9])

result = tf.nn.softmax(x)
result

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([4.5138627e-04, 2.7307284e-03, 9.9681783e-01], dtype=float32)>

## 15. Crea un modelo de Keras de tipo *Sequential* con nombre `images_model`.

In [25]:
images_model = keras.models.Sequential()
images_model

<Sequential name=sequential_1, built=False>

## 16. Añade una capa densa de $50$ neuronas con la función de activación *relu* a un modelo.

In [24]:
images_model.add(keras.layers.Dense(50, activation="relu"))
images_model

<Sequential name=sequential, built=False>