# NumPy Array (1-10) - Hugo Peralta Muñoz

Import NumPy

In [1]:
import numpy as np

#### 1. Write a NumPy program to print the NumPy version on your system.

In [2]:
print(np.version.version)

2.1.2


#### 2. Write a NumPy program to convert a list of numeric values into a one dimensional NumPy array.

`original_list = [12.23, 13.32, 100, 36.32]`

In [3]:
original_list = [12.23, 13.32, 100, 36.32]

numpy_array = np.array(original_list)

print(original_list)
print(numpy_array)

[12.23, 13.32, 100, 36.32]
[ 12.23  13.32 100.    36.32]


#### 3.  Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

In [5]:
matrix = np.arange(2, 11)

matrix_3x3 = matrix.reshape(3, 3)

print(matrix)
print(matrix_3x3)

[ 2  3  4  5  6  7  8  9 10]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


#### 4.  Write a NumPy program to create a null vector of size 10 and update the sixth value to 11.

In [6]:
null_vector = np.zeros(10)

null_vector[6] = 11

print(null_vector)

[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


#### 5. Write a NumPy program to create an array with values ranging from 12 to 38.


In [7]:
array = np.arange(12, 39)

print(array)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]


#### 6. Write a NumPy program to reverse an array (the first element becomes the last).

`original_array = [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]`

In [10]:
original_array = np.arange(12, 38)

reversed_array = original_array[::-1]

print(original_array)
print(reversed_array)


[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


#### 7. Write a NumPy program to convert an array to a floating type. 

In [11]:
int_array = np.arange(1, 5, dtype=int)

float_array = np.array(int_array, dtype=float)

print(int_array)
print(float_array)

[1 2 3 4]
[1. 2. 3. 4.]


#### 8. Write a NumPy program to create a 2D array with 1 on the border and 0 inside.


In [8]:
array = np.ones((5, 5))

print(array)

array[1:-1, 1:-1] = 0 # Coloca ceros en todas las filas menos la primera y la ultima, al igual que con las columnas

print(array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 9. Write a NumPy program to add a border (filled with 0's) around an existing array.

In [12]:
array = np.arange(1, 26).reshape(5, 5)

print(array)

array = np.pad(array, pad_width=1)

print(array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  0]
 [ 0  6  7  8  9 10  0]
 [ 0 11 12 13 14 15  0]
 [ 0 16 17 18 19 20  0]
 [ 0 21 22 23 24 25  0]
 [ 0  0  0  0  0  0  0]]


#### 10. Write a NumPy program to create an 8x8 matrix and fill it with a checkerboard pattern.

In [25]:
checkerboard = np.zeros(64, dtype=int).reshape(8, 8)

print(checkerboard)

checkerboard[::2, 1::2] = 1
checkerboard[1::2, ::2] = 1

print(checkerboard)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
