# NumPy Basic (21-30) - Hugo Peralta Muñoz

Importar dependencias

In [12]:
import numpy as np

### 21. Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.

In [13]:
vector = np.linspace(5, 50, 10)
print(vector)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


### 22. Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.


In [14]:
vector = np.arange(21)
print(vector)

vector[np.logical_and(vector >= 9, vector <= 15)] *= -1
print(vector)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


### 23. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.

In [15]:
rand_vector = np.random.randint(0, 11, 5)
print(rand_vector)

[ 7  1  4  4 10]


### 24. Write a NumPy program to multiply the values of two given vectors.

In [16]:
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

result = vector1 * vector2
print(result)

[ 4 10 18]


### 25. Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.


In [17]:
matrix = np.arange(10, 22).reshape(3, 4)
print(matrix)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


### 26. Write a NumPy program to find the number of rows and columns in a given matrix.

In [18]:
print(matrix.shape[0])
print(matrix.shape[1])

3
4


### 27. Write a NumPy program to create a 3x3 identity matrix, i.e. the diagonal elements are 1, the rest are 0.


In [19]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 28. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [20]:
square_matrix = np.zeros((10, 10))
square_matrix[0, :] = 1
square_matrix[-1, :] = 1
square_matrix[:, 0] = 1
square_matrix[:, -1] = 1


print(square_matrix)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 29. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [21]:
zero_matrix = np.zeros((5, 5))
np.fill_diagonal(zero_matrix, [1, 2, 3, 4, 5])
print(zero_matrix)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


## 30. Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.

In [23]:
 matrix = np.zeros(shape=(4, 4))
 matrix[::2, 1::2] = 1
 matrix[1::2, ::2] = 1

 print(matrix)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]
