NumPy Array (21-30) - Hugo Peralta Muñoz

Importar dependencias

In [1]:
import numpy as np

### 21. Write a NumPy program to find the set exclusive-or of two arrays. Set exclusive-or will return sorted, distinct values in only one (not both) of the input arrays.
`array1 = [ 0 10 20 40 60 80]`

`array2 = [10, 30, 40, 50, 70]`

Unique values that are in only one (not both) of the input arrays:
`[ 0 20 30 50 60 70 80]`


In [2]:
array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = np.array([10, 30, 40, 50, 70])

np.setxor1d(array1, array2)

array([ 0, 20, 30, 50, 60, 70, 80])

### 22. Write a NumPy program to find the union of two arrays. Union will return a unique, sorted array of values in each of the two input arrays.
`array1 = [ 0 10 20 40 60 80]`

`array2 = [10, 30, 40, 50, 70]`

Unique sorted array of values that are in either of the two input arrays:
`[ 0 10 20 30 40 50 60 70 80]`


In [3]:
array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = np.array([10, 30, 40, 50, 70])

np.union1d(array1, array2)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80])

### 23. Write a NumPy program to test whether all elements in an array evaluate to True.
**Note: 0 evaluates to False in NumPy**

In [5]:
test_array = np.array([1, 2, 3, 4, 5])

np.all(test_array)

False

### 24. Write a NumPy program to test whether any array element along a given axis evaluates to True.
**Note: 0 evaluates to False in NumPy.**


In [8]:
test_array = np.array([
                       [1, 2, 0, 4, 5],
                       [6, 7, 0, 9, 8]
                       ])

print(np.any(test_array, axis=0)) # Array evaluando por columnas
print(np.any(test_array, axis=1)) # Array evaluando por filas

[ True  True False  True  True]
[ True  True]


### 25. Write a NumPy program to construct an array by repeating.
Sample array: `[1, 2, 3, 4]`

Expected Output:
- Original array
`[1, 2, 3, 4]`

- Repeating 2 times
`[1 2 3 4 1 2 3 4]`

- Repeating 3 times
`[1 2 3 4 1 2 3 4 1 2 3 4]`

In [10]:
original_array = np.array([1, 2, 3, 4])

print(original_array)
print(np.tile(original_array, 2))
print(np.tile(original_array, 3))

[1 2 3 4]
[1 2 3 4 1 2 3 4]
[1 2 3 4 1 2 3 4 1 2 3 4]


### 26. Write a NumPy program to repeat array elements.
Sample array: `[1, 2, 3, 4]`

Expected Output:

`[1 1 2 2 3 3 4 4]`

In [12]:
original_array = np.array([1, 2, 3, 4])

print(original_array)
print(np.repeat(original_array, 2))

[1 2 3 4]
[1 1 2 2 3 3 4 4]


### 27. Write a NumPy program to find the indices of the maximum and minimum values along the given axis of an array.
Original array: `[1 2 3 4 5 6]`

Maximum Values: 5

Minimum Values: 0

In [14]:
original_array = np.array([1, 2, 3, 4, 5, 6]) # Va desde los indices 0 - 5, ya que contiene 6 elementos

print(np.argmax(original_array))
print(np.argmin(original_array))

5
0


### 28. Write a NumPy program to compare two arrays using NumPy.
Array a: `[1 2]`

Array b: `[4 5]`

a > b

`[False False]`

a >= b

`[False False]`

a < b

`[ True True]`

a <= b

`[ True True]`

In [15]:
array_a = [1, 2]
array_b = [4, 5]

print(np.greater(array_a, array_b))
print(np.greater_equal(array_a, array_b))
print(np.less(array_a, array_b))
print(np.less_equal(array_a, array_b))

[False False]
[False False]
[ True  True]
[ True  True]


### 29. Write a NumPy program to sort along the first and last axes of an array.
Sample array: `[[2,5],[4,4]]`

Expected Output:
- Original array:`
[[4 6]
[2 1]]`
- Sort along the first axis:`
[[2 1]
[4 6]]`
- Sort along the last axis:`
[[1 2]
[4 6]]`

In [17]:
original_array = np.array([[4, 6], [2, 1]])

print(original_array, end="\n\n")
print(np.sort(original_array, axis=0)) # First axis, filas
print()
print(np.sort(original_array, axis=1)) # Last axis, columnas

[[4 6]
 [2 1]]

[[2 1]
 [4 6]]

[[4 6]
 [1 2]]


### 30. Write a NumPy program to sort pairs of a first name and a last name and return their indices (first by last name, then by first name).
`first_names = (Betsey, Shelley, Lanell, Genesis, Margery)`

`last_names = (Battle, Brien, Plotner, Stahl, Woolum)`

Expected Output:
`[0 3 2 4 1]`

In [19]:
first_names = ('Betsey', 'Shelley', 'Lanell', 'Genesis', 'Margery')
last_names = ('Battle', 'Brien', 'Plotner', 'Stahl', 'Woolum')

np.lexsort((last_names, first_names))

array([0, 3, 2, 4, 1])