# NumPy Basic (1-20) - Hugo Peralta Muñoz

Import NumPy

In [2]:
import numpy as np

#### 1. Write a Numpy program to get the Numpy version and show the Numpy build configuration.


In [4]:
print(np.version.version)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139863411681952
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
   

#### 2. Write a NumPy program to get help with the add function.

In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 3. Write a NumPy program to test whether none of the elements of a given array are zero.

La función `numpy.all()` devuelve un valor booleano dependiendo de los cero que contenga el array introducido.

* `True`: Si todos los elementos del array son distintos de cero.
* `False`: Si algún valor del array es cero. 

In [5]:
array = np.ones([3, 3], dtype=int)

# Descomentar la linea inferior para comprobar el resultado contrario
#array[1, 2] = 0
print(array)

# la función 
print(np.all(array))

[[1 1 1]
 [1 1 0]
 [1 1 1]]
False


#### 4. Write a NumPy program to test if any of the elements of a given array are non-zero.

La función `numpy.any()` devuelve un valor booleano en función de los cero que contenga el array provisto.

* `True`: Si alguno de sus elementos es distinto de cero.
* `False`: Si todos sus elementos son cero.

In [7]:

array = np.zeros([3, 3], dtype=int)

# Descomentar la linea inferior para comprobar el resultado contrario
# array[1, 2] = 1
print(array)

# La función any devuelve true si alguno de sus elementos es distinto de cero o falso si todos sus elementos son cero
print(np.any(array))


[[0 0 0]
 [0 0 0]
 [0 0 0]]
False


#### 5. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a number).

La función `numpy.isfinite()` devuelve un array de booleanos comprobando todos los valores del array proporcionado individualmente.

Si un valor es:
* `True`: Significa que es un número finito.
* `False`: Significa que es un número infinito o no es un número.

In [17]:
array_finitos_o_infinitos = np.array([np.inf, 0, -np.inf, np.nan]) # nan = Not A Number
print(array_finitos_o_infinitos)

print(np.isfinite(array_finitos_o_infinitos))

[ inf   0. -inf  nan]
[False  True False False]


#### 6. Write a NumPy program to test elements-wise for positive or negative infinity.

La función `numpy.isinf()` devuelve un array comprobando los valores del array que se introduce.

Si su valor es:
* `True`: El elemento es infinito.
* `False`: El elemento es finito.

In [19]:
print(array_finitos_o_infinitos)
print(np.isinf(array_finitos_o_infinitos))

[ inf   0. -inf  nan]
[ True False  True False]


#### 7. Write a NumPy program to test element-wise for NaN of a given array.

Podemos usar la función que trae numpy, `numpy.isnan()` que nos devuelve en forma de booleano si el elemento o los elementos a valorar son numéricos o no. NaN = Not a Number. 

In [20]:
print(array_finitos_o_infinitos)
print(np.isnan(array_finitos_o_infinitos))

[ inf   0. -inf  nan]
[False False False  True]


#### 8. Write a NumPy program to test element-wise for complex numbers, real numbers in a given array. Also test if a given number is of a scalar type or not

Para comprobar si un número es complejo o no podemos usar el método `numpy.iscomplex()` que devuelve un booleano o un array de booleanos dependiendo de si el elementos o array de elementos introducido son complejos o no. 

***Nota importante: No considera complejo a un número si éste es cero en la parte imaginaria.***

Si queremos comprobar que un número sea escalar o no podremos usar la función `numpy.isscalar()`

Los valores escalares se refieren a como bien dice su nombre, valores escalares, como el volumen, tamaño, etc.

***Al mostrar los arrays, podemos mostrarlo con comas si añadimos la función `repr()` a la hora de mostrar por pantalla.***

In [27]:
numbers = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])

print(repr(numbers)) # Con repr() mostramos los valores del array con comas
print(np.iscomplex(numbers))

print(np.isscalar(5))
print(np.isscalar(3.7))
print(np.isscalar([3.7]))
print(np.isscalar(np.array(3.1)))
print(np.isscalar("asd"))
print(np.isscalar(True))
print(np.isscalar("numpy"))
print(np.isscalar(5j))

array([1. +1.j, 1. +0.j, 4.5+0.j, 3. +0.j, 2. +0.j, 0. +2.j])
[ True False False False False  True]
True
True
False
False
True
True
True
True


#### 9. Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.

Para realizar este ejercicio deberemos saber lo que hace la función `numpy.allclose()`, este método toma dos valores iniciales que son los arrays a comparar y dentro de un rango de tolerancia relativo y absoluto, calcula si son valores aproximados y devuelve un booleano en correspondencia.

Si la siguiente función es True, entonces `allclose()` devuelve True:
* `absolute(a - b) <= (atol + rtol * absolute(b))`. Esta función no es simétrica, el resultado puede variar según el orden en el que introduzcamos los valores.

In [41]:
a = np.array([1.0, 2.0, 3.00001]) # Entra en el rango relativo de tolerancia por defecto que es 1e+-5
b = np.array([1.0, 2.0, 3.0])
c = np.array([1.0, 2.0, 3.0001])

print(np.allclose(a, b))
print(np.allclose(b, c))

print(np.allclose([1e10,1e-7], [1.00001e10,1e-8]))
print(np.allclose([1e10,1e-8], [1.00001e10,1e-9]))

print(np.allclose([1.0, np.nan], [1.0, np.nan]))
print(np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True))

True
False
False
True


#### 10. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [42]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 1, 3])

print(np.greater(a, b))
print(np.greater_equal(a, b))
print(np.less(a, b))
print(np.less_equal(a, b))

[False False  True  True]
[False  True  True  True]
[ True False False False]
[ True  True False False]


#### 11. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.

Para ir de elemento a elemento usaremos la función `numpy.isclose()`.

In [49]:
a = np.array([1.0000001, 2.0, 3.0])
b = np.array([1.0, 2.0, 3.0001])

print(np.equal(a, b)) # Lo mismo que a == b
print(np.isclose(a, b)) # Aproximado

[False  True False]
[ True  True False]


#### 12. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

In [65]:
array = np.array([1, 7, 13, 105, 54], dtype=int) # 8 bytes por cada número del array

print(array)
print(array.nbytes)

[  1   7  13 105  54]
40


#### 13. Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives. 

In [7]:
ceros = np.zeros(10, dtype=int)
unos = np.ones(10, dtype=int)
cincos = np.full(10, 5)

print(ceros)
print(unos)
print(cincos)

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]
[5 5 5 5 5 5 5 5 5 5]


#### 14. Write a NumPy program to create an array of integers from 30 to 70.

In [8]:
array_range = np.arange(30, 71)

print(array_range)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


#### 15. Write a NumPy program to create an array of all even integers from 30 to 70

In [10]:
even_array = np.arange(30, 71, 2)

print(even_array)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


#### 16. Write a NumPy program to create a 3x3 identity matrix.

In [11]:
identity_array = np.identity(3)

print(identity_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 17. Write a NumPy program to generate a random number between 0 and 1.

In [17]:
rng = np.random.default_rng() 

random_num = rng.random() # Por defecto, el rango del random es desde el 0 al 1

print(random_num)

0.45505757242741807


#### 18. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [18]:
random_array = rng.random(15)

print(random_array)

[0.57626579 0.79703469 0.18703757 0.38819373 0.77535942 0.48327702
 0.3027586  0.20796035 0.44749834 0.1250663  0.33196206 0.80054308
 0.0252215  0.09523756 0.88399444]


#### 19. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.


In [25]:
random_array = np.random.randint(15, 56, size=10)

print(random_array)
print(random_array[1:-1])

[31 44 50 27 26 26 53 55 27 46]
[44 50 27 26 26 53 55 27]


#### 20. Write a NumPy program to create a 3X4 array and iterate over it.

In [30]:
a = np.random.randint(10, size=(3, 4))

print(a)


for fila in range(a.shape[0]):    # Iterar sobre las filas
    for columna in range(a.shape[1]): # Iterar sobre las columnas
        print(f"Elemento en ({fila}, {columna}):", a[fila, columna])


[[0 2 0 2]
 [9 9 1 7]
 [1 9 1 2]]
Elemento en (0, 0): 0
Elemento en (0, 1): 2
Elemento en (0, 2): 0
Elemento en (0, 3): 2
Elemento en (1, 0): 9
Elemento en (1, 1): 9
Elemento en (1, 2): 1
Elemento en (1, 3): 7
Elemento en (2, 0): 1
Elemento en (2, 1): 9
Elemento en (2, 2): 1
Elemento en (2, 3): 2
