# NumPy Basics (41-59) - Hugo Peralta Muñoz

Importar dependencias

In [ ]:
import numpy as np

### 41. Write a NumPy program to convert numpy dtypes to native Python types


In [ ]:
arr = np.array([1, 2, 3], dtype=np.int32)

native_type_arr = arr.astype(int).tolist()

print(arr)
print(native_type_arr)


[1 2 3]
[1, 2, 3]


### 42. Write a NumPy program to add elements to a matrix. If an element in the matrix is 0, we will not add the element below this element.

In [ ]:
def add_elements(matrix):
    rows, cols = matrix.shape

    total_sum = 0

    for i in range(rows):
        for j in range(cols):
            if matrix[i, j] == 0 and i < rows - 1:
                matrix[i + 1, j] = 0
            total_sum += matrix[i, j]

    return total_sum

matrix = np.array([[1, 2, 6],
                   [4, 0, 0],
                   [7, 8, 9]])

result = add_elements(matrix)
print("Sum of elements:", result)

Sum of elements: 20


### 43. Write a NumPy program to find missing data in a given array.


In [ ]:
array = np.array([[1, 2, 3],
                  [4, np.nan, 6],
                  [7, 8, 9]])

missing_data = np.isnan(array)

print(missing_data)

[[False False False]
 [False  True False]
 [False False False]]


### 44. Write a NumPy program to check whether two arrays are equal (element wise) or not.


In [ ]:
array_1 = np.array([1, 2, 3])
array_2 = np.array([1, 2, 3])

are_equal = np.array_equal(array_1, array_2)

print(are_equal)

True


### 45. Write a NumPy program to create a one-dimensional array of single, two and three-digit numbers.

In [ ]:
one_dimensional_array = np.arange(1, 10)
two_dimensional_array = np.arange(10, 100)
three_dimensional_array = np.arange(100, 1000)

print(one_dimensional_array)
print(two_dimensional_array)
print(three_dimensional_array)

[1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207
 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225
 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243
 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260 261
 262 263 264 265 266 267 268 269 270 271 272 273

### 46. Write a NumPy program to create a two-dimensional array of a specified format.

In [ ]:
print(np.arange(100).reshape(5, -1)) # El -1 crea un numero de columnas equitativo para el numero de elementos del array: 100 / 5 (filas) = 20 columnas

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]


### 47. Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values. Select random numbers from a uniform distribution between 0 and 1.

In [ ]:
random_numbers = np.random.uniform(0, 1, 40)
print(random_numbers)

[0.91397852 0.67726867 0.14387783 0.18927809 0.84980417 0.39444824
 0.40303595 0.54944893 0.60534393 0.29028191 0.9448725  0.38454782
 0.04824241 0.96802874 0.79631581 0.86668283 0.08660986 0.09255811
 0.57411909 0.90830762 0.37075541 0.18270747 0.34706044 0.55715821
 0.10524472 0.78219634 0.78133828 0.35224134 0.97282928 0.14005371
 0.66530113 0.3831364  0.6763974  0.70603935 0.02359761 0.21008276
 0.20866243 0.7976263  0.72708763 0.98923674]


### 48. Write a NumPy program to create a two-dimensional array with shape (8,5) of random numbers. Select random numbers from a normal distribution (200,7).

In [ ]:
random_array = np.random.normal(200, 7, size=(8, 5))
print(random_array)

[[201.69101979 197.3303295  205.97349151 185.64578337 208.42082193]
 [203.16997926 192.67418704 193.50466419 206.13923764 186.13425734]
 [207.9982019  196.57624979 194.05489632 211.13517234 198.51240002]
 [192.77715454 195.53735771 192.52502468 200.04302286 201.79557833]
 [188.95140765 206.56479245 200.75243825 191.24612484 207.81716803]
 [196.2009223  206.32997457 194.11928116 201.58165882 200.40682776]
 [196.51737779 193.27955163 198.02819278 189.87500652 186.13032874]
 [201.34073374 199.4556979  196.22243258 205.02018937 202.84081071]]


### 49. Write a NumPy program to generate a uniform, non-uniform random sample from a given 1-D array with and without replacement.


In [ ]:
uniform_array = np.random.choice(1, 10)
non_uniform_array = np.random.choice(10, 5, replace=False)

print(uniform_array)
print(non_uniform_array)

[0 0 0 0 0 0 0 0 0 0]
[1 2 9 3 7]


### 50. Write a NumPy program to create a 4x4 array with random values. Create an array from the said array swapping first and last rows.

In [ ]:
matrix = np.random.randint(0, 10, (4, 4))
print(matrix)

matrix[[0, -1]] = matrix[[-1, 0]]
print(matrix)

[[4 6 3 8]
 [8 0 6 3]
 [5 8 4 4]
 [3 9 3 3]]
[[3 9 3 3]
 [8 0 6 3]
 [5 8 4 4]
 [4 6 3 8]]


### 51. Write a NumPy program to create a new array of given shape (5,6) and type, filled with zeros.

In [ ]:
zero_array = np.zeros((5, 6), dtype=np.int32)
print(zero_array)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


### 52. Write a NumPy program to sort a given array by row and column in ascending order.

In [ ]:
array = np.array([[6, 5, 4],
                  [3, 2, 1],
                  [9, 8, 7]])

sorted_by_rows = np.sort(array, axis=0)
sorted_by_columns = np.sort(array, axis=1)

sorted_array = np.array(np.sort(np.sort(array, axis=0), axis=1))

print(sorted_by_rows)
print(sorted_by_columns)
print()
print(sorted_array)

[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[4 5 6]
 [1 2 3]
 [7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 53. Write a NumPy program to extract all numbers from a given array less and greater than a specified number.

In [ ]:
def extract_numbers(array, threshold):
    less_than_threshold = array[array < threshold]
    greater_than_threshold = array[array > threshold]
    return less_than_threshold, greater_than_threshold

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
threshold = 5

less, greater = extract_numbers(array, threshold)

print(threshold)
print(less)
print(greater)

5
[1 2 3 4]
[6 7 8 9]


### 54. Write a NumPy program to replace all numbers in a given array equal, less and greater than a given number.


In [ ]:
random_array = np.random.randint(0, 10, 10)

threshold = 5
replacement = 0

print(f"Original array: {random_array}")
print(np.where(random_array == threshold, replacement, random_array))
print(np.where(random_array < threshold, replacement, random_array))
print(np.where(random_array > threshold, replacement, random_array))

Original array: [6 9 1 2 1 4 6 6 3 9]
[6 9 1 2 1 4 6 6 3 9]
[6 9 0 0 0 0 6 6 0 9]
[0 0 1 2 1 4 0 0 3 0]


### 55. Write a NumPy program to create an array of equal shape and data type for a given array.


In [ ]:
array_1 = np.array([[1, 2, 3],
                    [4, 5, 6]], dtype=np.int32)

array_2 = np.zeros_like(array_1, dtype=array_1.dtype)

print(f"Array 1: {array_1.dtype}")
print(f"Array 2: {array_2.dtype}")
print(array_1)
print(array_2)

Array 1: int32
Array 2: int32
[[1 2 3]
 [4 5 6]]
[[0 0 0]
 [0 0 0]]


### 56. Write a NumPy program to create a three-dimensional array with the shape (3,5,4) and set it to a variable.


In [ ]:
three_dimensional_array = np.random.randint(0, 10, (3, 5, 4))

print(three_dimensional_array.shape)
print(three_dimensional_array.ndim)
print(three_dimensional_array)

(3, 5, 4)
3
[[[8 0 3 4]
  [2 6 4 9]
  [7 2 5 3]
  [7 8 0 0]
  [1 0 7 3]]

 [[2 8 2 5]
  [7 7 8 7]
  [2 8 0 0]
  [8 5 9 9]
  [7 0 6 9]]

 [[2 6 0 9]
  [7 9 8 5]
  [4 7 3 5]
  [1 6 1 4]
  [4 8 0 8]]]


### 57. Write a NumPy program to create a 4x4 array. Create an array from said array by swapping first and last, second and third columns.

In [ ]:
matrix = np.random.randint(0, 10, (4, 4))
print(matrix, end="\n\n")

matrix[[0, -1]] = matrix[[-1, 0]]
matrix[[1, 2]] = matrix[[2, 1]]
print(matrix)

[[2 6 2 7]
 [1 5 5 6]
 [5 6 1 4]
 [4 5 3 8]]

[[4 5 3 8]
 [5 6 1 4]
 [1 5 5 6]
 [2 6 2 7]]


### 58. Write a NumPy program to swap rows and columns of a given array in reverse order.

In [ ]:
original_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

swapped_array = original_array[::-1, ::-1]

print(original_array, end="\n\n")
print(swapped_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[9 8 7]
 [6 5 4]
 [3 2 1]]


### 59. Write a NumPy program to multiply two given arrays of the same size element-by-element.

In [ ]:
array_1 = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

array_2 = np.ones((3, 3), dtype=int) * 2

print(array_1, end="\n\n")
print(array_2, end="\n\n")
print(np.multiply(array_1, array_2)) # Igual que usar el simbolo "*"

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2 2 2]
 [2 2 2]
 [2 2 2]]

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
