NumPy Array (11-20) - Hugo Peralta Muñoz

In [16]:
import numpy as np

### 11. Write a NumPy program to convert a list and tuple into arrays.

List to array:
`[1 2 3 4 5 6 7 8]`

Tuple to array:
`[
  [8 4 2],
  [1 2 3]
]`

In [17]:
list_array = np.array([1, 2, 3, 4, 5, 6, 7, 8])
tuple_array = np.array([(8, 4, 2), (1, 2, 3)])

print(np.info(list_array))
print()
print(np.info(tuple_array))

class:  ndarray
shape:  (8,)
strides:  (8,)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x58655ec9e530
byteorder:  little
byteswap:  False
type: int64
None

class:  ndarray
shape:  (2, 3)
strides:  (24, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x58655eb9afe0
byteorder:  little
byteswap:  False
type: int64
None


### 12. Write a NumPy program to append values to the end of an array.

Expected Output:

Original array:
`[10, 20, 30]`

After appending values to the end of the array:
`[10 20 30 40 50 60 70 80 90]`

In [18]:
original_array = [10, 20, 30]
new_values = [40, 50, 60, 70, 80, 90]

new_array = np.append(original_array, new_values)

print(original_array)
print()
print(new_array)

[10, 20, 30]

[10 20 30 40 50 60 70 80 90]


### 13. Write a NumPy program to create an empty and full array.

Expected Output:

```
[ 6.93270651e-310 1.59262180e-316 6.93270559e-310 6.93270665e310]
[ 6.93270667e-310 6.93270671e-310 6.93270668e-310 6.93270483e310]
[ 6.93270668e-310 6.93270671e-310 6.93270370e-310 6.93270488e310]]

[[6 6 6]
[6 6 6]
[6 6 6]]
```

In [19]:
empty_array = np.empty((3, 3))
full_array = np.full((3, 3), 6)

print(empty_array)
print()
print(full_array)

[[4.80098295e-310 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]

[[6 6 6]
 [6 6 6]
 [6 6 6]]


### 14. Write a NumPy program to convert Centigrade degrees into Fahrenheit degrees. Centigrade values are stored in a NumPy array.

Sample Array

`[0, 12, 45.21, 34, 99.91]`

`[-17.78, -11.11, 7.34, 1.11, 37.73, 0. ]`

Expected Output:

Values in Fahrenheit degrees:

`[ 0. 12. 45.21 34. 99.91 32. ]`

Values in Centigrade degrees:

`[-17.78 -11.11 7.34 1.11 37.73 0. ]`

In [20]:
fahrenheit_degrees = np.array([0., 12., 45.21, 34., 99.91, 32.])
centigrade_degrees = np.around(np.array(fahrenheit_degrees - 32) * 5 / 9, 2)

print(fahrenheit_degrees)
print()
print(centigrade_degrees)

[ 0.   12.   45.21 34.   99.91 32.  ]

[-17.78 -11.11   7.34   1.11  37.73   0.  ]


### 15. Write a NumPy program to find the real and imaginary parts of an array of complex numbers.

Expected Output:

Original array `[ 1.00000000+0.j 0.70710678+0.70710679j]`

Real part of the array:
`[ 1. 0.70710678]`

Imaginary part of the array:
`[ 0. 0.70710679]`

In [21]:
original_array = np.array([1.00000000+0.j, 0.70710678+0.70710679j])
real_part_array = np.real(original_array)
imaginary_part_array = np.imag(original_array)

print(original_array, end="\n\n")
print(real_part_array, end="\n\n")
print(imaginary_part_array, end="\n\n")

[1.        +0.j         0.70710678+0.70710679j]

[1.         0.70710678]

[0.         0.70710679]



### 16. Write a NumPy program to find the number of elements in an array. It also finds the length of one array element in bytes and the total bytes consumed by the elements.
Expected Output:

Size of the array: 3

Length of one array element in bytes: 8

Total bytes consumed by the elements of the array: 24

In [22]:
array = np.array([1, 2, 3])

print(f"Size of the array: {array.size}")
print(f"Length of one array element in bytes: {array.itemsize}")
print(f"Total bytes consumed by the elements of the array: {array.nbytes}")

Size of the array: 3
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 24


### 17. Write a NumPy program to test whether each element of a 1-D array is also present in a second array.
Expected Output:

`array1 = [ 0 10 20 40 60]`

`array2 = [0, 40]`

Compare each element of array1 and array2

`[ True False False True False]`

In [23]:
array1 = [0, 10, 20, 40, 60]
array2 = [0, 40]

np.in1d(array1, array2)

array([ True, False, False,  True, False])

### 18. Write a NumPy program to find common values between two arrays.
Expected Output:

`array1 = [ 0 10 20 40 60]`

`array2 = [10, 30, 40]`

Common values between two arrays:
`[10 40]`


In [24]:
array1 = [0, 10, 20, 40, 60]
array2 = [10, 30, 40]

np.intersect1d(array1, array2)

array([10, 40])

### 19. Write a NumPy program to get the unique elements of an array.
Expected Output:

Original array:
`[10 10 20 20 30 30]`

Unique elements of the above array:
`[10 20 30]`


In [25]:
original_array = np.array([10, 10, 20, 20, 30, 30])
unique_array = np.unique(original_array)

print(original_array)
print()
print(unique_array)

[10 10 20 20 30 30]

[10 20 30]


### 20. Write a NumPy program to find the set difference between two arrays. The set difference will return sorted, distinct values in array1 that are not in array2.

Expected Output:

`array1 = [ 0 10 20 40 60 80]`

`array2 = [10, 30, 40, 50, 70, 90]`

Set difference between two arrays:
`[ 0 20 60 80]`

In [27]:
array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = np.array([10, 30, 40, 50, 70, 90])

np.setdiff1d(array1, array2) # A diferencia del intersect1d que devuelve los valores unicos que coinciden ambos arrays,
                             # el setdiff1d devuelve los valores unicos del primer array que no estan en el segundo

array([ 0, 20, 60, 80])