# NumPy

NumPy (Numerical Python) es una librería estandar para el uso de arrays en Python. NumPy se utiliza mucho con Pandas, SciPy, Matplotlib, ScikitLearn, ScikitImage y la mayoría de paquetes científicos de Python.

In [1]:
# Importación de NumPy
import numpy as np

## Array de NumPy vs Lista

Lista de Python:

* Puede contener elementos de distinto tipo.

Array de NumPy:

* Muy rápido.
* Ocupa menos en memoria.
* Permite muchas operaciones matemáticas.

In [ ]:
lista = [5, "siete", 20, True]
print(type(lista))
print(lista)

<class 'list'>
[5, 'siete', 20, True]


In [ ]:
import numpy as np

array1 = np.array([5, "siete", 20, True])
print(type(array1))
print(type(array1.dtype))
print(array1)

<class 'numpy.ndarray'>
<class 'numpy.dtypes.StrDType'>
['5' 'siete' '20' 'True']


In [ ]:
array2 = np.array([5, 7, 20, -8])
print(type(array2.dtype))
print(array2)

<class 'numpy.dtypes.Int64DType'>
[ 5  7 20 -8]


## Arrays de una dimensión

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)
print(a[0])
print(a[1])
print(a[-1])

[1 2 3 4 5 6]
1
2
6


## Arrays de dos dimensiones

In [ ]:
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]])

print(a)
print(a[0])
print(a[2][1])
print(a[-1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]
10


## Dimensiones del array

In [ ]:
array_3d = np.array([
    [[1, 2, 3, 4], [5, 6, 7, 8]],
    [[9, 10, 11, 12], [13, 14, 15, 16]]
])

In [ ]:
print(array_3d.ndim)
print(array_3d.size)
print(array_3d.shape)

## Creación de arrays basicos

In [ ]:
np.zeros(10)
print(np.zeros(10), int)
print(np.zeros(10))

In [ ]:
# np.empty crea un array sin inicializar
# Los valores son los que hay en memoria en el momento de reservar para el array
# La creación de estos arrays es muy rapida
a = np.empty(10)
print(a)
print(a.dtype)

In [ ]:
a = np.empty(10, np.int16)
print(a)
print(a.dtype)

[-15662 -21664  22272      0      0      0      0      0    101      0]
int16


In [ ]:
a = np.empty([10, 3], str)

In [ ]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.arange(20, 40, 2)

In [ ]:
# Numeros separados de forma equitativa en un intervalo

np.linspace(-10, 10, num=5, dtype=int)

array([-10,  -5,   0,   5,  10])

### Ejercicio

Define una función, con la cabecera que se indica a continuación, que rellene un array de NumPy con los n primeros números primos.

`def numpy_primes(n):`

**Ej:** `numpy_primes(10)` -> `array[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]`

In [ ]:
from sympy import isprime

def numpy_primes(n):
    array = np.empty(n, int)

    i = 0
    j = 0
    while i < n:
        if isprime(j):
            array[i] = j
            i += 1
        j += 1
    return array

print(numpy_primes(10))
print(len(numpy_primes(10)))

[ 2  3  5  7 11 13 17 19 23 29]
10


## Ordenar elementos

In [ ]:
b = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(b)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.sort(b)[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1])

## Añadir y quitar elementos

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

np.concatenate((a, b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
x = np.array([
    [1, 2], [4, 5]
    ])
y = np.array([
    [6, 7], [9, 10]
    ])

z = np.concatenate((x, y), axis=0) # Axis = 0 referencia a la primera dimension, las filas
                                   # Axis = 1 referencia a la segunda dimension, las columnas
                                   # Axis = 2 referencia a la tercera dimension, la profundidad
print(z)

[[ 1  2  6  7]
 [ 4  5  9 10]]


In [2]:
data = np.array(
    [
        [1, 2],
        [3, 4],
        [5, 6],
        [7, 8]
    ]
)

print(data)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [5]:
print(data[0, 1])
print(data[1:3])
print(data[0:2, 0]) # Devuelve un array de una dimension, si queremos sacarlo en un array de dos dimensiones hacer la traspuesta: transpose()

2
[[3 4]
 [5 6]]
[1 3]
[[2]
 [4]]


## Cambiar las dimensiones de un array

In [6]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [7]:
b = a.reshape(3, 2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [8]:
c = a.reshape(3, 2, 1)
c

array([[[0],
        [1]],

       [[2],
        [3]],

       [[4],
        [5]]])

In [17]:
# Crear una funcion reshape_zeros que haga lo mismo que reshape pero que rellene con ceros los huecos

# Opcion 1, sirve para arrays de x dimensiones
def reshape_zeros(original_array, shape): # shape sera una tupla
    new_array = np.zeros(shape, dtype=int)

    # Nos permite no preocuparnos de las dimensiones, hace que un array multidimensional se convierta en una dimension
    flatten_array = original_array.flatten()

    new_array.flat[:len(flatten_array)] = flatten_array

    return new_array

reshape_zeros(a, (5, 3))

# Opcion 2
def reshape_zeros2(a, dimensiones):
  filas, columnas = dimensiones
  longitud = a.size
  f_x_c = filas * columnas
  if longitud == f_x_c:
    array0 = a.reshape(dimensiones)
  else:
    a = a.reshape(1, longitud)
    a = a[0]
    c = f_x_c - longitud
    if c < 0:
      array0 = a[ :f_x_c]
    else:
      array0 = np.concatenate((a, np.zeros(c, int)))
    array0 = array0.reshape(dimensiones)
  return array0

print(reshape_zeros2(np.array([[1.2, 2], [3, 4]]), (3, 5)))

# Opcion 3
def reshape_zeros3(array_entrada, dimensiones):
  filas, columnas = dimensiones
  tamanio = array_entrada.size

  if filas * columnas == tamanio:
    a = array_entrada.reshape(dimensiones)
    return a

  elif filas * columnas > tamanio:
    b = np.zeros((filas * columnas) - tamanio, int)
    return np.concatenate((array_entrada, b)).reshape(dimensiones)
  else:
    longitud = np.prod(dimensiones)
    array_entrada.resize(longitud , refcheck=False)
    return array_entrada.reshape(dimensiones)

reshape_zeros3(a, (1, 6))

array([[0, 1, 2],
       [3, 4, 5],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
a = np.arange(100, 112)
a

In [ ]:
b = np.reshape(4, -1) # Se infiere la segunda dimension

## Filtros

In [20]:
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

In [22]:
print(a[a < 5])

[1 2 3 4]


In [21]:
mayores_que_cinco = (a > 5)
print(a[mayores_que_cinco])

[ 6  7  8  9 10 11 12]


In [24]:
pares = a[a % 2 == 0]
print(pares)

[ 2  4  6  8 10 12]


In [25]:
a > 4

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

## Mezcla de índices

In [27]:
a = np.array([4, 8, 20, 31, 44, 7, 9, 13])
b = np.array([4, 2, 0, 3])
print(a)
print(b)

[ 4  8 20 31 44  7  9 13]


array([4, 2, 0, 3])

In [28]:
print(a[b]) # Coge los elementos del array b y son los indices de los numeros del array a lo que devuelve

[44 20  4 31]


## Operaciones con arrays

In [36]:
data = np.array([1, 2])
unos = np.ones(2, dtype=int)
unos += unos

In [37]:
data + unos

array([3, 4])

In [38]:
data * unos

array([2, 4])

In [39]:
data / unos

array([0.5, 1. ])

In [40]:
data // unos

array([0, 1])

In [41]:
a = np.arange(5, 15)
print(a)
print(a.sum())
print(a.min())
print(a.max())

[ 5  6  7  8  9 10 11 12 13 14]
95
5
14


In [47]:
b = np.array(
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ]
)

c = np.array(
    [
        [3, 3],
        [4, 4],
        [5, 5],
        [6, 6]
    ]
)

print(b)
print(b.sum(axis=0)) # Suma de las columnas
print(b.sum(axis=1)) # Suma de las filas
print(b.cumsum(axis=0)) # Suma acumulada de las columnas
print(b.cumsum(axis=1)) # Suma acumulada de las filas
np.dot(b, c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[15 18 21 24]
[10 26 42]
[[ 1  2  3  4]
 [ 6  8 10 12]
 [15 18 21 24]]
[[ 1  3  6 10]
 [ 5 11 18 26]
 [ 9 19 30 42]]


array([[ 50,  50],
       [122, 122],
       [194, 194]])

In [46]:
b * 1.6

array([[ 1.6,  3.2,  4.8,  6.4],
       [ 8. ,  9.6, 11.2, 12.8],
       [14.4, 16. , 17.6, 19.2]])

## Arrays aleatorios

In [48]:
rng = np.random.default_rng() # Inicialización de los aleatorios

In [51]:
a = rng.integers(11, size=(3, 4)) # Crea un array de 3 filas y 4 columnas con numeros aleatorios entre 0 y 10
a

array([[9, 2, 3, 2],
       [0, 7, 7, 8],
       [9, 9, 5, 3]])

In [52]:
a = np.random.randint(11, size=(3, 4)) # Crea un array de 3 filas y 4 columnas con numeros aleatorios entre 0 y 10
a

array([[ 7, 10,  9,  7],
       [ 0,  2,  7,  0],
       [ 3,  7,  6,  3]])